### ISSUE TITLE
Can you recommend background information or papers about this method

### ISSUE THREAD

**Issue by ChristiaanWewer** [CuAuPro/fuzzy-predictive-control#1]
Hey, 
I am very interested in this method, however I'd like to read a bit more into the background knowledge of the method you have created. Can you maybe recommend me some papers/books that elaborate this?
Cheers!

**Comment by CuAuPro** [comment]
Hello @ChristiaanWewer.

I appreciate your expressed interest in implementation of that method.

Unfortunately, the literature used for this implementation is not available as it was intended exclusively for our faculty's student use. To learn more, I suggest looking into resources on Predictive Functional Controllers and equation derivations for state-space models.

Similar literature:
1. I Skrjanc and D Matko. Fuzzy predictive functional control in the state space domain. Journal of Intelligent
and Robotic Systems, 31(1–3):283–297, 2001.

2. M Lepetic, I Skrjanc, H G Chiacchiarini, and D Matko. Predictive functional control based on fuzzy model:
magnetic suspension system case study. Engineering Applications of Artificial Intelligence, 16:425–430, 2003

3. FUZZY PREDICTIVE CONTROL: CONTINUOUS STIRRED–TANK REACTOR CASE STUDY“, IFAC Proceedings Volumes, let. 35, št. 1, str. 91–96, jan. 2002, doi: [10.3182/20020721-6-ES-1901.01568](https://doi.org/10.3182/20020721-6-ES-1901.01568).

Best regards!

**Comment by ChristiaanWewer** [comment]
Thank you very much! This is really useful material that helps me forward 😊.
Cheers!

**Comment by CuAuPro** [comment]
@ChristiaanWewer, no problem. If you have any specific questions, you can also reach me via e-mail or LinkedIn.

Cheers!
